# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [2]:
chipo = pd.read_csv("chipotle.tsv", sep="\t")
chipo.item_price = chipo.item_price.str.replace("$", "", regex=False).astype(float)

### Step 4. How many products cost more than $10.00?

In [3]:
chipo_one_item = chipo[chipo.quantity == 1]
chipo_one_item[chipo_one_item.item_price > 10].item_name.nunique()

25

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [4]:
price_per_item = chipo_one_item[["item_name", "item_price"]].drop_duplicates()
price_per_item.sort_values("item_name")

              item_name  item_price
298   6 Pack Soft Drink        6.49
4510      Barbacoa Bowl       11.49
95        Barbacoa Bowl        9.25
115       Barbacoa Bowl        8.99
3195      Barbacoa Bowl        8.69
...                 ...         ...
186   Veggie Salad Bowl       11.25
960   Veggie Salad Bowl        8.75
781   Veggie Soft Tacos        8.75
1395  Veggie Soft Tacos        8.49
738   Veggie Soft Tacos       11.25

[135 rows x 2 columns]

### Step 6. Sort by the name of the item

In [5]:
chipo.item_name.sort_values()

3389    6 Pack Soft Drink
341     6 Pack Soft Drink
1849    6 Pack Soft Drink
1860    6 Pack Soft Drink
2713    6 Pack Soft Drink
              ...
2384    Veggie Soft Tacos
781     Veggie Soft Tacos
2851    Veggie Soft Tacos
1699    Veggie Soft Tacos
1395    Veggie Soft Tacos
Name: item_name, Length: 4622, dtype: object

### Step 7. What was the quantity of the most expensive item ordered?

In [6]:
chipo.sort_values("item_price", ascending=False)[["item_name", "quantity", "item_price"]].head(1)

                         item_name  quantity  item_price
3598  Chips and Fresh Tomato Salsa        15       44.25

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [7]:
chipo[chipo.item_name == "Veggie Salad Bowl"].shape[0]

18

### Step 9. How many times did someone order more than one Canned Soda?

In [8]:
chipo[(chipo.item_name == "Canned Soda") & (chipo.quantity > 1)].shape[0]

20